---
title: "premier-refresh"
date: "`r Sys.time()`"
output: html_document
---

```{r libraries constants, include=F}
# get start time of script
start_time <- Sys.time()

# libraries
library(odbc)
library(DBI)
library(glue)
library(dplyr)
library(tidyr)
library(dbplyr)
library(digest)
library(doParallel)
library(lubridate)

# dev and prod dsn strings
dev_dsn <- "OAO Cloud DB Staging"
prod_dsn <- "OAO Cloud DB Production"

# radiant volume directory
rad_dir <- paste0("/SharedDrive/deans/Presidents/SixSigma/MSHS Productivity/",
                  "Productivity/Volume - Data/Multisite Volumes/",
                  "Radiology - Radiant/")

# constants for ~# of days back to refresh/upload
x_days <- 90
query_date <- Sys.Date() - x_days

# get pay period of 90 days prior
prod_con <- dbConnect(odbc(), prod_dsn)
paycycle <- tbl(prod_con, "LPM_MAPPING_PAYCYCLE") %>% 
  collect() %>%
  mutate(PAYCYCLE_DATE = as.Date(PAYCYCLE_DATE)) %>%
  filter(PAYCYCLE_DATE >= as.Date(query_date))
query_date <- min(paycycle$PP_START_DATE)

# get max date for premier upload
max_date <- paycycle %>% 
  select(PP_END_DATE, PREMIER_DISTRIBUTION) %>%
  distinct() %>%
  mutate(PP_END_DATE = as.Date(PP_END_DATE)) %>%
  filter(PP_END_DATE < floor_date(Sys.Date(), unit = "month"),
         PREMIER_DISTRIBUTION == 1) %>%
  arrange(desc(PP_END_DATE)) %>%
  select(PP_END_DATE) %>%
  slice_head() %>% 
  pull()
  
# get current row count in LPM_RAD_PREMIER
row_count <- tbl(prod_con, "LPM_RAD_PREMIER") %>%
  summarise(n()) %>%
  collect() %>%
  pull()

# function for creating insert statements on LPM_RAD_PREMIER
get_values_premier <- function(source_table, destination_schema, destination_table) {
  
    CORPORATION_CODE <- source_table[1]  #VARCHAR(6 char)
    ENTITY_CODE      <- source_table[2]  #VARCAHR(6 char)
    COSTCENTER       <- source_table[3]  #VARCAHR(15 char)
    PP_START_DATE    <- source_table[4]  #DATE
    PP_END_DATE      <- source_table[5]  #DATE
    SERVICE_DATE     <- source_table[6]  #NUMERIC
    CPT4             <- source_table[7]  #VARCHAR(15 char)
    ACTUAL_VOLUME    <- source_table[8]  #DATE
    DATE_ADDED       <- source_table[9]  #DATE
    
    values <- glue("INTO {glue::double_quote(destination_schema)}.{glue::double_quote(destination_table)}
                   (CORPORATION_CODE, ENTITY_CODE , COSTCENTER, PP_START_DATE, PP_END_DATE, SERVICE_DATE,
                   CPT4, ACTUAL_VOLUME, DATE_ADDED)
                 
                   VALUES ('{CORPORATION_CODE}', '{ENTITY_CODE}', '{COSTCENTER}', 
                   TO_DATE('{PP_START_DATE}', 'yyyy-mm-dd'), TO_DATE('{PP_END_DATE}', 'yyyy-mm-dd'), 
                   TO_DATE('{SERVICE_DATE}', 'yyyy-mm-dd'), '{CPT4}', '{ACTUAL_VOLUME}',
                   TO_DATE('{DATE_ADDED}', 'yyyy-mm-dd'))")
    
    return(values)
}
```

# Truncate Staging
```{r truncate staging, echo=FALSE}
truncate_upload <- glue("TRUNCATE TABLE LPM_RAD_PREMIER_STAGING;")

# execute mapping table merge statements
dev_con <- dbConnect(odbc(), dev_dsn)
dbBegin(dev_con)

# execute statements and if there is an error  with one of them rollback changes
tryCatch({
  dbExecute(dev_con, truncate_upload)
  print("LPM_RAD_PREMIER_STAGING has been truncated")
  
  dbCommit(dev_con)
  dbDisconnect(dev_con)
  
  print(paste0(Sys.time(), ": Staging Table Truncated Successfully"))
  }, 
  error = function(err){
    dbRollback(dev_con)
    dbDisconnect(dev_con)
    print("Error")
    }
  )
```

# Delete 90 Day
```{r delete 90 day, echo=FALSE}
delete_90_day <- glue(
  "DELETE FROM LPM_RAD_PREMIER
   WHERE SERVICE_DATE >= DATE \'{query_date}\';")

# execute delete query
prod_con <- dbConnect(odbc(), prod_dsn)
dbBegin(prod_con)
dbExecute(prod_con, delete_90_day)
dbCommit(prod_con)
dbDisconnect(prod_con)

print(paste0(Sys.time(), ": The last 90 days have been deleted from LPM_RAD_PREMIER"))
```

# Data Pull
```{r combined data pull, echo=FALSE}
# prod connection
prod_con <- dbConnect(odbc(), prod_dsn)

premier_insert <- glue(
  "WITH RESOURCE_LOGIC AS (
    SELECT rad.*,
           CASE WHEN RESOURCE_NAME = 'MSB CT 1' AND
                     substr(EXAM,1,2) IN ('IR','NS')
               THEN 'MSB IN 1'
               WHEN RESOURCE_NAME = 'BC PET CT 1' AND
                    substr(EXAM,1,6) = 'NM PET'
               THEN 'BC PET INJECTIONS'
               ELSE RESOURCE_NAME
        END RESOURCE_NAME_LOGIC
    FROM LPM_RAD_COMBINED rad
    WHERE SERVICE_DATE >= DATE \'{query_date}\'),
   RAD_JOINED AS (
    SELECT
        rad.*,
        paycycle.PP_START_DATE,
        paycycle.PP_END_DATE,
        cc.COSTCENTER,
        support.SUPPORT,
        '729805' as CORPORATION_CODE,
        CASE WHEN support.SUPPORT IN ('MSH', 'MSQ') THEN 'NY0014'
             WHEN support.SUPPORT IN ('MSB', 'MSUS', 'CCW') THEN '630571'
             WHEN support.SUPPORT = 'MSW' THEN 'NY2162'
             WHEN support.SUPPORT = 'MSM' THEN 'NY2163'
             WHEN rad.RESOURCE_NAME = 'MSH 1176 RAD CT' THEN 'NY0014'
        END ENTITY_CODE
   FROM RESOURCE_LOGIC rad
   LEFT JOIN LPM_MAPPING_PAYCYCLE paycycle ON rad.SERVICE_DATE = paycycle.PAYCYCLE_DATE
   LEFT JOIN LPM_RAD_MAPPING_COSTCENTER cc ON rad.RESOURCE_NAME_LOGIC = cc.RESOURCE_NAME
   LEFT JOIN LPM_RAD_MAPPING_SUPPORT support ON rad.RESOURCE_NAME_LOGIC = support.RESOURCE_NAME
   WHERE cc.COSTCENTER IS NOT NULL)
   SELECT
        CORPORATION_CODE,
        ENTITY_CODE,
        COSTCENTER,
        PP_START_DATE,
        PP_END_DATE,
        SERVICE_DATE,
        CPT4,
        COUNT(*) as ACTUAL_VOLUME
   FROM RAD_JOINED
   GROUP BY
        CORPORATION_CODE,
        ENTITY_CODE,
        COSTCENTER,
        PP_START_DATE,
        PP_END_DATE,
        SERVICE_DATE,
        CPT4;")


# create, execute and clear result for premier radiant query
premier_insert_query <- dbSendQuery(prod_con, premier_insert)
radiant_premier <- dbFetch(premier_insert_query)
dbClearResult(premier_insert_query)

# add unique ID and date added columns
radiant_premier <- radiant_premier %>%
  mutate(
    SERVICE_DATE = as.character(as.Date(SERVICE_DATE)),
    PP_END_DATE = as.character(as.Date(PP_END_DATE)),
    PP_START_DATE = as.character(as.Date(PP_START_DATE)),
    DATE_ADDED = as.character(Sys.Date()))
  
print(paste0(Sys.time(), ": Premier Data Pulled Successfully"))
```

# Insert Staging Table
```{r radiant premier staging, echo=FALSE}
rad_premier_schema <- "OAO_DEVELOPMENT"
rad_premier_table <- "LPM_RAD_PREMIER_STAGING"
# convert the each record/row of tibble to INTO clause of insert statement
inserts <- 
  lapply(
    lapply(
      lapply(split(radiant_premier, 
                   1:nrow(radiant_premier)),
             as.list),
      as.character),
    FUN = get_values_premier, rad_premier_schema, rad_premier_table)

# create batches of inserts for insert statements
chunk_length <- 250
split_queries <- split(inserts, ceiling(seq_along(inserts)/chunk_length))

# append each batch of inserts to batch insert list
split_queries_values <- list()
for (i in 1:length(split_queries)) {
  row <- glue_collapse(split_queries[[i]], sep = "\n\n")
  values <- glue('INSERT ALL
               {row}
               SELECT 1 from DUAL;')
  split_queries_values <- append(split_queries_values, values)
}

# execute parallel inserts of 250 record chunks
registerDoParallel()
outputPar <- foreach(i = 1:length(split_queries_values), 
                     .packages = c("DBI", "odbc")) %dopar% {
                       dev_con <- dbConnect(odbc(), dev_dsn)
                       tryCatch({
                         dbBegin(dev_con)
                         dbExecute(dev_con, split_queries_values[[i]])
                         dbCommit(dev_con)
                         dbDisconnect(dev_con)
                       },
                       error = function(err){
                         print("error")
                         dbRollback(dev_con)
                         dbDisconnect(dev_con)
                       })
                     }
registerDoSEQ()
print(paste0(Sys.time(), ": Premier rad data has been added to LPM_RAD_PREMIER_STAGING"))
```

# Insert To PROD
```{r insert prod, echo=FALSE}
insert_premier <- glue(
  "INSERT INTO LPM_RAD_PREMIER
   SELECT * 
   FROM OAO_DEVELOPMENT.LPM_RAD_PREMIER_STAGING;" 
)

# prod connection
prod_con <- dbConnect(odbc(), prod_dsn)

# execute statements and if there is an error  with one of them rollback changes
tryCatch({
  dbBegin(prod_con)
  
  dbExecute(prod_con, insert_premier)
  print("LPM_RAD_PREMIER_STAGING has been inserted to LPM_RAD_PREMIER")
  
  dbCommit(prod_con)
  dbDisconnect(prod_con)
  
  print(paste0(Sys.time(), ": Production Table Updated Successfully"))
  }, 
  error = function(err){
    dbRollback(prod_con)
    dbDisconnect(prod_con)
    print("Error")
    }
  )

# prod connection
prod_con <- dbConnect(odbc(), prod_dsn)

# get total rows after data has been merged
total_rows_after_insert <- tbl(prod_con, "LPM_RAD_PREMIER") %>%
  summarise(n()) %>%
  collect() %>%
  pull()
```

# Create Zero Upload
```{r premier zero, echo=FALSE}
# read in most recent upload file
zero_files <- file.info(list.files(paste0(rad_dir, "uploads/"),
                             full.names = T,
                             pattern = "*.csv")) %>%
    arrange(desc(mtime))
zero <- read.csv(rownames(zero_files)[1],
               check.names = FALSE) %>%
  filter(as.Date(`Start Date`, format = "%m/%d/%Y") >= as.Date(query_date)) %>%
  mutate(`Actual Volume` = '0')

# get max date of zero file
max_zero <- max(as.Date(zero$`End Date`, format = "%m/%d/%Y"))

# save 90 day premier upload
write.csv(zero, paste0(rad_dir, "uploads/zero/MSHS_RADIANT ZERO_",
                                 query_date, "_", max_zero, ".csv"),
          row.names = FALSE)

print(paste0(Sys.time(), ": Premier Zero Upload Created Successfully"))
```

# Create Premier Upload
```{r premier upload, echo=FALSE}
# prod connection
prod_con <- dbConnect(odbc(), prod_dsn)

# pull last 90 days of data from production
premier_query <- glue(
  "SELECT CORPORATION_CODE, 
          ENTITY_CODE, 
          COSTCENTER, 
          PP_START_DATE,
          PP_END_DATE, 
          CPT4,
          sum(ACTUAL_VOLUME) as ACTUAL_VOLUME
   FROM LPM_RAD_PREMIER
   WHERE SERVICE_DATE >= DATE \'{query_date}\' AND
         SERVICE_DATE <= DATE \'{max_date}\'
   GROUP BY CORPORATION_CODE, 
            ENTITY_CODE, 
            COSTCENTER, 
            PP_START_DATE,
            PP_END_DATE, 
            CPT4;")

# create, execute and clear result for premier radiant query
premier_query <- dbSendQuery(prod_con, premier_query)
premier_upload <- dbFetch(premier_query)
dbClearResult(premier_query)

# pull all unique cc 
unique_cc <- tbl(prod_con, "LPM_RAD_MAPPING_COSTCENTER") %>%
  filter(!is.na(COSTCENTER)) %>%
  distinct() %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_SUPPORT") %>%
              mutate(SUPPORT = case_when(
                RESOURCE_NAME == 'MSH 1176 RAD CT' ~ "MSH",
                TRUE ~ SUPPORT)),
            by = c("RESOURCE_NAME" = "RESOURCE_NAME")) %>%
  select(COSTCENTER, SUPPORT) %>%
  collect()

# pull unique pp for upcoming upload
unique_pp <- tbl(prod_con, "LPM_MAPPING_PAYCYCLE") %>%
  collect() %>%
  filter(as.Date(PAYCYCLE_DATE) >= as.Date(query_date),
         as.Date(PAYCYCLE_DATE) <= as.Date(max_date)) %>%
  select(PP_START_DATE, PP_END_DATE) %>%
  distinct() 

# make df of all unique combos of pp and cc in upload
unique_combo <- expand_grid(unique_cc, unique_pp) %>%
  mutate()

# join unique combos with upload to find cc's without data and fill in gaps
unique_upload <- premier_upload %>%
  full_join(unique_combo, 
             by = c("COSTCENTER" = "COSTCENTER",
                    "PP_START_DATE" = "PP_START_DATE",
                    "PP_END_DATE" = "PP_END_DATE")) %>%
  mutate(CORPORATION_CODE = '729805',
         ENTITY_CODE = case_when(
           is.na(ENTITY_CODE) & SUPPORT %in% c("MSB", "CCW", "MSUS") ~ "630571",
           is.na(ENTITY_CODE) & SUPPORT %in% c("MSH", "MSQ") ~ "NY0014",
           is.na(ENTITY_CODE) & SUPPORT == "MSW" ~ "NY2162",
           is.na(ENTITY_CODE) & SUPPORT == "MSM" ~ "NY2163",
           TRUE ~ ENTITY_CODE),
         CPT4 = case_when(
           is.na(CPT4) ~ "71045",
           TRUE ~ CPT4),
         ACTUAL_VOLUME = case_when(
           is.na(ACTUAL_VOLUME) ~ 0,
           TRUE ~ ACTUAL_VOLUME)) %>%
  select(-SUPPORT)

# further format for premier upload 
premier_upload <- unique_upload %>%
  mutate(`Budget Volume` = '0',
         PP_START_DATE = format(PP_START_DATE, "%m/%d/%Y"),
         PP_END_DATE = format(PP_END_DATE, "%m/%d/%Y")) %>%
  rename(`Corporation Code` = CORPORATION_CODE,
         `Entity Code` = ENTITY_CODE,
         `Cost Center Code` = COSTCENTER,
         `Start Date` = PP_START_DATE,
         `End Date` = PP_END_DATE,
         `CPT Code` = CPT4,
         `Actual Volume` = ACTUAL_VOLUME)

# save 90 day premier upload
write.csv(premier_upload, paste0(rad_dir, "uploads/MSHS_RADIANT_",
                                 query_date, "_", max_date, ".csv"),
          row.names = FALSE)

print(paste0(Sys.time(), ": Premier Upload Created Successfully"))
```

# Execution Details
```{r runtime, echo=FALSE}
# calc how long it took to knit markdown
runtime = round(as.numeric(difftime(Sys.time(), start_time, units = c("mins"))), digits = 2)

print(paste("Radiant Refresh took", runtime, "minutes to complete"))
print(paste("Radiant data was refreshed back to", as.character(query_date)))
print(paste(nrow(radiant_premier), "rows were inserted into LPM_RAD_PREMIER"))
```