---
title: "radiant-backfill-`r params$monthyear`"
date: "`r Sys.time()`"
output: html_document
params:
  start_date: NULL
  monthyear: NULL
---

```{r libraries constants, include=F}
library(odbc)
library(DBI)
library(glue)
library(dplyr)
library(tidyr)
library(dbplyr)
library(digest)
library(doParallel)
library(lubridate)

mods <- c('26', 'TC', '53', '50')

### Additional Exam Logic --------------------------------------------------
# Exam codes starting with "IR" or "NS" on resource "MSB CT 1" belong to IR
MSB_CT_1 <- c("IR", "NS")
# Exam codes starting with "NM PET" on resource "BC PET CT 1" belong to IR
BC_PET_CT_1 <- "NM PET"

start_date <- params$start_date
end_date <- as.character(rollforward(as.Date(start_date)))
start_time <- Sys.time()

dev_dsn <- "OAO Cloud DB Staging"
prod_dsn <- "OAO Cloud DB Production"

get_values_rad <- function(source_table, destination_schema, destination_table) {
  
    SERVICE_DATE      <- source_table[1] # DATE,
    PP_END_DATE       <- source_table[2] # DATE,
    ORDER_ID          <- source_table[3] # VARCHAR2(10 char),
    ACCESSION         <- source_table[4] # VARCHAR2(15 char),
    EXAM              <- source_table[5] # VARCHAR2(150 char),
    PARENT_LOCATION   <- source_table[6] # VARCHAR2(50 char),
    LOCATION          <- source_table[7] # VARCHAR2(50 char),
    DEPARTMENT        <- source_table[8] # VARCHAR2(50 char),
    BASE_CLASS        <- source_table[9] # VARCHAR2(15 char),
    ACCT_CLASS        <- source_table[10] # VARCHAR2(50 char),
    VISIT             <- source_table[11] # VARCHAR2(20 char),
    RESOURCE_NAME     <- source_table[12] # VARCHAR2(100 char),
    MODALITY          <- source_table[13] # VARCHAR2(50 char),
    CPT4              <- source_table[14] # VARCHAR2(15 char),
    EPIC_ID           <- source_table[15] # VARCHAR2(15 char),
    EPIC_NAME         <- source_table[16] # VARCHAR2(100 char),
    SUPPORT           <- source_table[17] # VARCHAR2(15 char),
    DEFINITION_CODE   <- source_table[18] # VARCHAR2(15 char),
    DEFINITION_NAME   <- source_table[19] # VARCHAR2(60 char),
    COSTCENTER        <- source_table[20] # VARCHAR2(15 char),
    SOURCE_TABLE      <- source_table[21] # VARCHAR2(15 char),
    UNIQUE_ID         <- source_table[22] # VARCHAR2(50 char)
    
    values <- glue("INTO {glue::double_quote(destination_schema)}.{glue::double_quote(destination_table)}
                   (SERVICE_DATE, PP_END_DATE, ORDER_ID, ACCESSION, EXAM, PARENT_LOCATION, LOCATION, DEPARTMENT,     
                   BASE_CLASS, ACCT_CLASS, VISIT, RESOURCE_NAME, MODALITY, CPT4, EPIC_ID, EPIC_NAME, SUPPORT,        
                   DEFINITION_CODE, DEFINITION_NAME, COSTCENTER, SOURCE_TABLE, UNIQUE_ID)
                 
                   VALUES (TO_DATE('{SERVICE_DATE}', 'yyyy-mm-dd'), TO_DATE('{PP_END_DATE}', 'yyyy-mm-dd'),
                   '{ORDER_ID}', '{ACCESSION}', '{EXAM}', '{PARENT_LOCATION}', '{LOCATION}',
                   '{DEPARTMENT}', '{BASE_CLASS}', '{ACCT_CLASS}', '{VISIT}', '{RESOURCE_NAME}',
                   '{MODALITY}', '{CPT4}', '{EPIC_ID}', '{EPIC_NAME}', '{SUPPORT}', '{DEFINITION_CODE}',  
                   '{DEFINITION_NAME}', '{COSTCENTER}', '{SOURCE_TABLE}', '{UNIQUE_ID}')")
    
    return(values)
}

get_values_premier <- function(source_table, destination_schema, destination_table) {
    PARTNER          <- source_table[1] #VARCHAR2(10 char),
    ENTITY_CODE      <- source_table[2] #VARCHAR2(10 char),
    COST_CENTER_CODE <- source_table[3] #VARCHAR2(15 char),
    START_DATE       <- source_table[4] #DATE,
    END_DATE         <- source_table[5] #DATE,
    CPT_CODE         <- source_table[6] #VARCHAR2(15 char),
    ACTUAL_VOLUME    <- source_table[7] #NUMERIC,
    BUDGET_VOLUME    <- source_table[8] #VARCHAR2(5 char)
    UNIQUE_ID        <- source_table[9] #VARCHAR2(50 char)
    
    values <- glue("INTO {glue::double_quote(destination_schema)}.{glue::double_quote(destination_table)}
                   (PARTNER, ENTITY_CODE, COST_CENTER_CODE, START_DATE, END_DATE,
                   CPT_CODE, ACTUAL_VOLUME, BUDGET_VOLUME, UNIQUE_ID)
                 
                   VALUES ('{PARTNER}', '{ENTITY_CODE}', '{COST_CENTER_CODE}', 
                   TO_DATE('{START_DATE}', 'yyyy-mm-dd'), TO_DATE('{END_DATE}', 'yyyy-mm-dd'),
                   '{CPT_CODE}', '{ACTUAL_VOLUME}', '{BUDGET_VOLUME}', '{UNIQUE_ID}')")
}
```

# Merge Mapping Tables
```{r merge mapping tables, echo=FALSE}
merge_costcenter <- glue(
  "MERGE INTO LPM_RAD_MAPPING_COSTCENTER dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_COSTCENTER source
   ON (dest.RESOURCE_NAME = source.RESOURCE_NAME)
   WHEN MATCHED THEN
   UPDATE SET dest.COSTCENTER = source.COSTCENTER
   WHEN NOT MATCHED THEN
   INSERT (dest.RESOURCE_NAME,
           dest.COSTCENTER)
   VALUES (source.RESOURCE_NAME,
           source.COSTCENTER);")

merge_cpt_type <- glue(
  "MERGE INTO LPM_RAD_MAPPING_CPT_TYPE dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_CPT_TYPE source
   ON (dest.DEFINITION_CODE = source.DEFINITION_CODE)
   WHEN MATCHED THEN
   UPDATE SET dest.CPT_TYPE = source.CPT_TYPE
   WHEN NOT MATCHED THEN
   INSERT (dest.DEFINITION_CODE,
           dest.CPT_TYPE)
   VALUES (source.DEFINITION_CODE,
           source.CPT_TYPE);")

merge_epic_dep <- glue(
  "MERGE INTO LPM_RAD_MAPPING_EPIC_DEP dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_EPIC_DEP source
   ON (dest.RESOURCE_NAME = source.RESOURCE_NAME)
   WHEN MATCHED THEN
   UPDATE SET dest.EPIC_ID = source.EPIC_ID,
              dest.EPIC_NAME = source.EPIC_NAME
   WHEN NOT MATCHED THEN
   INSERT (dest.RESOURCE_NAME,
           dest.EPIC_ID,
           dest.EPIC_NAME)
   VALUES (source.RESOURCE_NAME,
           source.EPIC_ID,
           source.EPIC_NAME);")

merge_report <- glue(
  "MERGE INTO LPM_RAD_MAPPING_REPORT dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_REPORT source
   ON (dest.RESOURCE_NAME = source.RESOURCE_NAME)
   WHEN MATCHED THEN
   UPDATE SET dest.DEFINITION_CODE = source.DEFINITION_CODE,
              dest.DEFINITION_NAME = source.DEFINITION_NAME
   WHEN NOT MATCHED THEN
   INSERT (dest.RESOURCE_NAME,
           dest.DEFINITION_CODE,
           dest.DEFINITION_NAME)
   VALUES (source.RESOURCE_NAME,
           source.DEFINITION_CODE,
           source.DEFINITION_NAME);")

merge_support <- glue(
  "MERGE INTO LPM_RAD_MAPPING_SUPPORT dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_SUPPORT source
   ON (dest.RESOURCE_NAME = source.RESOURCE_NAME)
   WHEN MATCHED THEN
   UPDATE SET dest.SUPPORT = source.SUPPORT
   WHEN NOT MATCHED THEN
   INSERT (dest.RESOURCE_NAME,
           dest.SUPPORT)
   VALUES (source.RESOURCE_NAME,
           source.SUPPORT);")

merge_or <- glue(
  "MERGE INTO LPM_RAD_MAPPING_OR dest
   USING OAO_DEVELOPMENT.LPM_RAD_MAPPING_OR source
   ON (dest.RESOURCE_NAME = source.RESOURCE_NAME)
   WHEN NOT MATCHED THEN
   INSERT (dest.RESOURCE_NAME)
   VALUES (source.RESOURCE_NAME);")

# execute mapping table merge statements
prod_con <- dbConnect(odbc(), prod_dsn)
dbBegin(prod_con)

# execute statements and if there is an error  with one of them rollback changes
tryCatch({
  dbExecute(prod_con, merge_costcenter)
  print("LPM_RAD_MAPPING_COSTCENTER has been merged")
  dbExecute(prod_con, merge_cpt_type)
  print("LPM_RAD_MAPPING_CPT_TYPE has been merged")
  dbExecute(prod_con, merge_epic_dep)
  print("LPM_RAD_MAPPING_epic_dep has been merged")
  dbExecute(prod_con, merge_report)
  print("LPM_RAD_MAPPING_REPORT has been merged")
  dbExecute(prod_con, merge_support)
  print("LPM_RAD_MAPPING_SUPPORT has been merged")
  dbExecute(prod_con, merge_or)
  print("LPM_RAD_MAPPING_OR has been merged")
  
  dbCommit(prod_con)
  dbDisconnect(prod_con)
  
  print(paste0(Sys.time(), ": Mapping Tables Merged Successfully"))
  }, 
  error = function(err){
    dbRollback(prod_con)
    dbDisconnect(prod_con)
    print("Error")
    }
  )
```

# Data Pull
### Billing
```{r billing data pull, echo=FALSE}
prod_con <- dbConnect(odbc(), prod_dsn)

or_resource <- tbl(prod_con, "LPM_RAD_MAPPING_OR") %>%
  collect() %>%
  pull()

billing <- tbl(prod_con, "Y_IMG_PREMIER_LABOR_PRODUCTIVITY") %>%
  filter(POST_DATE >= as.Date(start_date),
         POST_DATE <= as.Date(end_date),
         !(RESOURCE %in% or_resource)) %>%
  mutate(
    MODIFIER_ONE = case_when(
      !(MODIFIER_ONE %in% mods) ~ "",
      TRUE ~ MODIFIER_ONE),
    MODIFIER_TWO = case_when(
      !(MODIFIER_TWO %in% mods) ~ "",
      TRUE ~ MODIFIER_TWO),
    MODIFIER_THREE = case_when(
      !(MODIFIER_THREE %in% mods) ~ "",
      TRUE ~ MODIFIER_THREE),
    MODIFIER_FOUR = case_when(
      !(MODIFIER_FOUR %in% mods) ~ "",
      TRUE ~ MODIFIER_FOUR),
    CPT4 = paste0(CHARGE, MODIFIER_ONE, MODIFIER_TWO, MODIFIER_THREE, MODIFIER_FOUR)) %>%
  left_join(tbl(prod_con, "LPM_MAPPING_PAYCYCLE"),
            by = c("SERVICE_DATE" = "PAYCYCLE_DATE")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_COSTCENTER"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_EPIC_DEP"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_SUPPORT"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_REPORT"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  rename(RESOURCE_NAME = RESOURCE) %>%
  mutate(
    DEFINITION_CODE = case_when(
      RESOURCE_NAME == "MSB CT 1" & substr(EXAM, 1, 2) %in% MSB_CT_1 ~ "MSB_RAD106",
      RESOURCE_NAME == "BC PET CT 1" & substr(EXAM, 1, 6) %in% BC_PET_CT_1 ~ "CCW_RAD108",
      TRUE ~ DEFINITION_CODE),
    DEFINITION_NAME = case_when(
      RESOURCE_NAME == "MSB CT 1" & substr(EXAM, 1, 2) %in% MSB_CT_1 ~ "INTERVENTIONAL RADIOLOGY",
      RESOURCE_NAME == "BC PET CT 1" & substr(EXAM, 1, 6) %in% BC_PET_CT_1 ~ "OP NUCLEAR MEDICINE/PET RADIOLOGY",
      TRUE ~ DEFINITION_NAME),
    SOURCE_TABLE = "BILLING") %>%
  select(SERVICE_DATE, PP_END_DATE, ORDER_ID, ACCESSION, EXAM, PARENT_LOCATION,
         LOCATION, DEPARTMENT, BASE_CLASS, ACCT_CLASS, VISIT, RESOURCE_NAME,
         MODALITY, CPT4, EPIC_ID, EPIC_NAME, SUPPORT, DEFINITION_CODE,
         DEFINITION_NAME, COSTCENTER, SOURCE_TABLE) %>%
  collect() %>%
  mutate(
    SERVICE_DATE = as.character(as.Date(SERVICE_DATE)),
    PP_END_DATE = as.character(as.Date(PP_END_DATE)),
    UNIQUE_ID = 
    paste0(SERVICE_DATE, PP_END_DATE, ORDER_ID, ACCESSION, EXAM, PARENT_LOCATION,
         LOCATION, DEPARTMENT, BASE_CLASS, ACCT_CLASS, VISIT, RESOURCE_NAME,
         MODALITY, CPT4, EPIC_ID, EPIC_NAME, SUPPORT, DEFINITION_CODE,
         DEFINITION_NAME, COSTCENTER, SOURCE_TABLE))
billing$UNIQUE_ID <- sapply(billing$UNIQUE_ID, digest, algo="md5")
  
print(paste0(Sys.time(), ": Billing Data Pulled Successfully"))
```

### Order
```{r order data pull, echo=FALSE}
prod_con <- dbConnect(odbc(), prod_dsn)

or_resource <- tbl(prod_con, "LPM_RAD_MAPPING_OR") %>%
  collect() %>%
  pull()

order <- tbl(prod_con, "Y_IMG_PREMIER_LABOR_PRODUCTIVITY_LNKD_CHGS") %>%
  mutate(SERVICE_DATE = to_date(DATE, 'YYYY-MM-DD')) %>%
  filter(SERVICE_DATE >= as.Date(start_date),
         SERVICE_DATE <= as.Date(end_date),
         RESOURCE %in% or_resource,
         CHARGE_TYPE == 'Technical') %>%
  left_join(tbl(prod_con, "LPM_MAPPING_PAYCYCLE"),
            by = c("SERVICE_DATE" = "PAYCYCLE_DATE")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_COSTCENTER"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_EPIC_DEP"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_SUPPORT"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  left_join(tbl(prod_con, "LPM_RAD_MAPPING_REPORT"),
            by = c("RESOURCE" = "RESOURCE_NAME")) %>%
  rename(RESOURCE_NAME = RESOURCE,
         CPT4 = CPT_CODE) %>%
  mutate(
    DEFINITION_CODE = case_when(
      RESOURCE_NAME == "MSB CT 1" & substr(EXAM, 1, 2) %in% MSB_CT_1 ~ "MSB_RAD106",
      RESOURCE_NAME == "BC PET CT 1" & substr(EXAM, 1, 6) %in% BC_PET_CT_1 ~ "CCW_RAD108",
      TRUE ~ DEFINITION_CODE),
    DEFINITION_NAME = case_when(
      RESOURCE_NAME == "MSB CT 1" & substr(EXAM, 1, 2) %in% MSB_CT_1 ~ "INTERVENTIONAL RADIOLOGY",
      RESOURCE_NAME == "BC PET CT 1" & substr(EXAM, 1, 6) %in% BC_PET_CT_1 ~ "OP NUCLEAR MEDICINE/PET RADIOLOGY",
      TRUE ~ DEFINITION_NAME),
    SOURCE_TABLE = "ORDER") %>%
  select(SERVICE_DATE, PP_END_DATE, ORDER_ID, ACCESSION, EXAM, PARENT_LOCATION,
         LOCATION, DEPARTMENT, BASE_CLASS, ACCT_CLASS, VISIT, RESOURCE_NAME,
         MODALITY, CPT4, EPIC_ID, EPIC_NAME, SUPPORT, DEFINITION_CODE,
         DEFINITION_NAME, COSTCENTER, SOURCE_TABLE) %>%
  collect() %>%
  mutate(
    SERVICE_DATE = as.character(as.Date(SERVICE_DATE)),
    PP_END_DATE = as.character(as.Date(PP_END_DATE)),
    UNIQUE_ID = 
    paste0(SERVICE_DATE, PP_END_DATE, ORDER_ID, ACCESSION, EXAM, PARENT_LOCATION,
         LOCATION, DEPARTMENT, BASE_CLASS, ACCT_CLASS, VISIT, RESOURCE_NAME,
         MODALITY, CPT4, EPIC_ID, EPIC_NAME, SUPPORT, DEFINITION_CODE,
         DEFINITION_NAME, COSTCENTER, SOURCE_TABLE))
order$UNIQUE_ID <- sapply(order$UNIQUE_ID, digest, algo="md5")


print(paste0(Sys.time(), ": Order Data Pulled Successfully"))
```

# Combine Data
```{r combine data, echo=FALSE}
combined <- rbind(billing, order)

print(paste0(Sys.time(), ": Billing & Order Data Combined Successfully"))
```

# Premier Upload Creation
```{r premier upload, echo=FALSE, message=FALSE}
premier <- combined %>% 
  mutate(PARTNER = '729805',
         ENTITY_CODE = case_when(
           SUPPORT %in% c('MSB', 'MSUS', 'CCW') ~ '630571',
           SUPPORT %in% c('MSH', 'MSQ') ~ 'NY0014',
           SUPPORT == 'MSW' ~ 'NY2162',
           SUPPORT == 'MSM' ~ 'NY2163'),
         START_DATE = SERVICE_DATE,
         END_DATE = SERVICE_DATE) %>%
  rename(COST_CENTER_CODE = COSTCENTER, 
         CPT_CODE = CPT4) %>%
  group_by(PARTNER, ENTITY_CODE, COST_CENTER_CODE, START_DATE, END_DATE, CPT_CODE) %>%
  summarise(ACTUAL_VOLUME = n()) %>%
  mutate(BUDGET_VOLUME = '0',
         UNIQUE_ID = paste0(PARTNER, ENTITY_CODE, COST_CENTER_CODE, START_DATE,
                            END_DATE, CPT_CODE, ACTUAL_VOLUME, BUDGET_VOLUME))
premier$UNIQUE_ID <- sapply(premier$UNIQUE_ID, digest, algo="md5")

print(paste0(Sys.time(), ": Premier Upload Created Successfully"))
```

# Truncate Tables
```{r truncate, echo=FALSE}
truncate_combined <- glue("TRUNCATE TABLE LPM_RAD_COMBINED_STAGING;")
truncate_upload <- glue("TRUNCATE TABLE LPM_RAD_UPLOAD_STAGING;")

# execute mapping table merge statements
dev_con <- dbConnect(odbc(), dev_dsn)
dbBegin(dev_con)

# execute statements and if there is an error  with one of them rollback changes
tryCatch({
  dbExecute(dev_con, truncate_combined)
  print("LPM_RAD_COMBINED_STAGING has been truncated")
  dbExecute(dev_con, truncate_upload)
  print("LPM_RAD_UPLOAD_STAGING has been truncated")
  
  dbCommit(dev_con)
  dbDisconnect(dev_con)
  
  print(paste0(Sys.time(), ": Staging Tables Truncated Successfully"))
  }, 
  error = function(err){
    dbRollback(dev_con)
    dbDisconnect(dev_con)
    print("Error")
    }
  )
```

# Insert Staging Tables
### Combined
```{r combined staging, echo=FALSE}
rad_combined_schema <- "OAO_DEVELOPMENT"
rad_combined_table <- "LPM_RAD_COMBINED_STAGING"
# convert the each record/row of tibble to INTO clause of insert statment
inserts <- 
  lapply(
    lapply(
      lapply(split(combined, 
                   1:nrow(combined)),
             as.list),
      as.character),
    FUN = get_values_rad, rad_combined_schema, rad_combined_table)

# create batches of inserts for insert statements
chunk_length <- 250
split_queries <- split(inserts, ceiling(seq_along(inserts)/chunk_length))

# append each batch of inserts to batch insert list
split_queries_values <- list()
for (i in 1:length(split_queries)) {
  row <- glue_collapse(split_queries[[i]], sep = "\n\n")
  values <- glue('INSERT ALL
               {row}
               SELECT 1 from DUAL;')
  split_queries_values <- append(split_queries_values, values)
}

# execute parallel inserts of 250 record chunks
registerDoParallel()
outputPar <- foreach(i = 1:length(split_queries_values), 
                     .packages = c("DBI", "odbc")) %dopar% {
                       dev_con <- dbConnect(odbc(), dev_dsn)
                       tryCatch({
                         dbBegin(dev_con)
                         dbExecute(dev_con, split_queries_values[[i]])
                         dbCommit(dev_con)
                         dbDisconnect(dev_con)
                       },
                       error = function(err){
                         print("error")
                         dbRollback(dev_con)
                         dbDisconnect(dev_con)
                       })
                     }
registerDoSEQ()
print(paste0(Sys.time(), ": Combined rad data has been added to LPM_RAD_COMBINED_STAGING"))
```

### Upload
```{r upload staging, echo=FALSE}
rad_premier_schema <- "OAO_DEVELOPMENT"
rad_premier_table <- "LPM_RAD_UPLOAD_STAGING"
# convert the each record/row of tibble to INTO clause of insert statment
inserts <- 
  lapply(
    lapply(
      lapply(split(premier, 
                   1:nrow(premier)),
             as.list),
      as.character),
    FUN = get_values_premier, rad_premier_schema, rad_premier_table)

# create batches of inserts for insert statements
chunk_length <- 250
split_queries <- split(inserts, ceiling(seq_along(inserts)/chunk_length))

# append each batch of inserts to batch insert list
split_queries_values <- list()
for (i in 1:length(split_queries)) {
  row <- glue_collapse(split_queries[[i]], sep = "\n\n")
  values <- glue('INSERT ALL
               {row}
               SELECT 1 from DUAL;')
  split_queries_values <- append(split_queries_values, values)
}

# execute parallel inserts of 250 record chunks
registerDoParallel()
outputPar <- foreach(i = 1:length(split_queries_values), 
                     .packages = c("DBI", "odbc")) %dopar% {
                       dev_con <- dbConnect(odbc(), dev_dsn)
                       tryCatch({
                         dbBegin(dev_con)
                         dbExecute(dev_con, split_queries_values[[i]])
                         dbCommit(dev_con)
                         dbDisconnect(dev_con)
                       },
                       error = function(err){
                         print("error")
                         dbRollback(dev_con)
                         dbDisconnect(dev_con)
                       })
                     }
registerDoSEQ()
print(paste0(Sys.time(), ": Premier upload data has been added to LPM_RAD_UPLOAD_STAGING"))
```

# Merge Staging to PROD
```{r merge staging, echo=FALSE}
merge_combined <- glue(
  "MERGE INTO LPM_RAD_COMBINED dest
   USING OAO_DEVELOPMENT.LPM_RAD_COMBINED_STAGING source
   ON (dest.UNIQUE_ID = source.UNIQUE_ID)
   WHEN NOT MATCHED THEN
   INSERT (
    dest.SERVICE_DATE,      
    dest.PP_END_DATE,       
    dest.ORDER_ID,         
    dest.ACCESSION,         
    dest.EXAM,              
    dest.PARENT_LOCATION,   
    dest.LOCATION,          
    dest.DEPARTMENT,        
    dest.BASE_CLASS,        
    dest.ACCT_CLASS,        
    dest.VISIT,             
    dest.RESOURCE_NAME,      
    dest.MODALITY,          
    dest.CPT4,              
    dest.EPIC_ID,           
    dest.EPIC_NAME,         
    dest.SUPPORT,           
    dest.DEFINITION_CODE,   
    dest.DEFINITION_NAME,   
    dest.COSTCENTER,        
    dest.SOURCE_TABLE,      
    dest.UNIQUE_ID)         
   VALUES (
    source.SERVICE_DATE,      
    source.PP_END_DATE,       
    source.ORDER_ID,         
    source.ACCESSION,         
    source.EXAM,              
    source.PARENT_LOCATION,   
    source.LOCATION,          
    source.DEPARTMENT,        
    source.BASE_CLASS,        
    source.ACCT_CLASS,        
    source.VISIT,             
    source.RESOURCE_NAME,      
    source.MODALITY,          
    source.CPT4,              
    source.EPIC_ID,           
    source.EPIC_NAME,         
    source.SUPPORT,           
    source.DEFINITION_CODE,   
    source.DEFINITION_NAME,   
    source.COSTCENTER,        
    source.SOURCE_TABLE,      
    source.UNIQUE_ID);")

merge_upload <- glue(
  "MERGE INTO LPM_RAD_UPLOAD dest
   USING OAO_DEVELOPMENT.LPM_RAD_UPLOAD_STAGING source
   ON (dest.UNIQUE_ID = source.UNIQUE_ID)
   WHEN NOT MATCHED THEN
   INSERT (
    dest.PARTNER,      
    dest.ENTITY_CODE,       
    dest.COST_CENTER_CODE,         
    dest.START_DATE,         
    dest.END_DATE,              
    dest.CPT_CODE,   
    dest.ACTUAL_VOLUME,          
    dest.BUDGET_VOLUME,      
    dest.UNIQUE_ID)         
   VALUES (
    source.PARTNER,      
    source.ENTITY_CODE,       
    source.COST_CENTER_CODE,         
    source.START_DATE,         
    source.END_DATE,              
    source.CPT_CODE,   
    source.ACTUAL_VOLUME,          
    source.BUDGET_VOLUME,      
    source.UNIQUE_ID);")

# execute mapping table merge statements
prod_con <- dbConnect(odbc(), prod_dsn)
dbBegin(prod_con)

# execute statements and if there is an error  with one of them rollback changes
tryCatch({
  dbExecute(prod_con, merge_combined)
  print("LPM_RAD_COMBINED has been merged")
  dbExecute(prod_con, merge_upload)
  print("LPM_RAD_UPLOAD has been merged")
  
  dbCommit(prod_con)
  dbDisconnect(prod_con)
  
  print(paste0(Sys.time(), ": Production Tables Merged Successfully"))
  }, 
  error = function(err){
    dbRollback(prod_con)
    dbDisconnect(prod_con)
    print("Error")
    }
  )
```

# Execution Details
```{r runtime, echo=FALSE}
runtime <- round(as.numeric(difftime(Sys.time(), start_time, units = c("mins"))), digits = 2)
monthyear <- format(as.Date(start_date), "%B-%Y")

print(paste("Radiant Refresh took", runtime, "minutes to complete"))
print(paste("Radiant data was backfilled for", monthyear))
```